- package-lock.json
- package.json
- Updating storybook and its dependencies to the new version. Tested locally and works fine.
- Add missing dependencies semantic-release
> update storybook + dependencies & add missing dependencies to do semantic-release

- README.md
- src/components/ui-label.vue
- src/stories/ui-badge.stories.js
- src/stories/ui-label.stories.js
The label component, I did not add tests as there is nothing functional to test on this component.
> Label component

- src/components/ui-notification.vue
- src/components/ui-toast.vue
- src/stories/ui-badge.stories.js
- src/stories/ui-button.stories.js
- src/stories/ui-label.stories.js
- src/stories/ui-notification.stories.js
- src/stories/ui-toast.stories.js
- tailwind.config.js
I've added the toast component, it's styles are directly converted so it should visually be exactly the same as it was previously. I was thining of adding tests, but then I'm not sure what to test on this one, I'm curious what you think here.
> Toast component

- .github/workflows/release.yml
https://github.com/semantic-release/git/issues/196#issuecomment-601310576
> chore(release): persist credentials false

- src/components/ui-select.vue
- src/stories/ui-select.stories.js
> Add ui-select component

- src/components/ui-checkbox.vue
- src/stories/ui-checkbox.stories.js
> Add checkbox component

- package-lock.json
- package.json
- src/components/ui-spinner.vue
- tailwind.config.js
> fix(tailwind): use config

- src/components/ui-button-group.vue
- src/stories/ui-button-group.stories.js
I added the button group component, it can take some buttons and will group them together just like it does in the funda ui button group component. Nothing fancy (yet), it just does exactly the same job as it's predecessor. It's very minimal and basic, a good start for iteration I figure. Let me know what you think.
> Button group

- src/components/ui-radio.vue
- src/stories/ui-radio.stories.js
Added this improvements as I was having issues with the value bindings in Flex-ui. 
Also added a name prop to add radio groups support
> feat(input-id): added support for radio groups using unique ids

- src/components/ui-checkbox-group.vue
- src/stories/ui-checkbox-group.stories.js
- src/stories/ui-checkbox.stories.js
Separated the checkbox input from the group for more flexibility
> feat(checkbox): seperated checkbox input from group

- README.md
- src/components/ui-icon.vue
- src/nuxt.js
This PR will merge ui components and nuxt components (in separate nuxt app). This way it becomes tree-shakable and can be imported automatically
https://nuxtjs.org/blog/improve-your-developer-experience-with-nuxt-components/#third-party-component-library
> Nuxt support

- package-lock.json
Nothing more, nothing less. The fix is for 13 vulnerabilities in the ini package.
> NPM audit fixes

- src/components/ui-select.vue
- src/stories/ui-select.stories.js
We would like to use placeholder values in selects, and so we need to bind the disabled state for options
> feat(select): Bind disabled and hidden for options

- package-lock.json
- package.json
I've added the grip and crop icons to the set, this PR updates the icons so we're aligned.
> feat(icons): update to the latest funda icons

- src/components/ui-card-image.vue
- src/components/ui-card.vue
- src/stories/ui-card.stories.js
I've found a need for a media slot in the ui-card, this is a pattern seen commonly in funda desk already. For this I added a slot and added styling to have the media always filling out the top of the card.
> Ui-card media slot

- package-lock.json
- package.json
- postcss.config.js
- src/components/ui-button.vue
- src/stories/ui-badge.stories.js
- src/stories/ui-icon.stories.js
- src/stories/ui-modal.stories.js
- src/stories/ui-notification.stories.js
- src/stories/ui-toast.stories.js
- src/stories/ui-tooltip.stories.js
- src/styles/styles.css
- tailwind.config.js
> feat(tailwind2): use tailwind2

- src/components/ui-modal.vue
- src/stories/ui-modal.stories.js
before: https://funda-frontend.github.io/ui/latest/?path=/story/layout-modal--modal-default
after: https://funda-frontend.github.io/ui/refs/pull/363/merge/?path=/story/layout-modal--modal-default
> fix(modal): only set full height when using wideMode

- src/components/ui-toast.vue
- src/components/ui-toaster.vue
- src/stories/ui-toast.stories.js
- src/stories/ui-toaster.stories.js
BREAKING CHANGE: toast component refactored to have no animation and be always visible
> feat(toaster): add toaster component

- src/components/ui-button.vue
- src/stories/ui-button.stories.js
I need to be able to overwrite the default height of the component
> feat(button): make it possible to change height

- package-lock.json
- package.json
- src/components/ui-spinner.vue
- src/stories/ui-spinner.stories.js
BREAKING CHANGE: the spinner component is less "opinionated", removed position absolute and negative margins
> fix(spinner): remove position absolute, scoped styles

- package-lock.json
- package.json
- src/components/ui-button.vue
- src/components/ui-input.vue
- src/components/ui-select.vue
- src/components/ui-textarea.vue
- src/stories/ui-button.stories.js
Main difference is the inner shadow for the inputs:
https://funda-frontend.github.io/ui/refs/pull/415/merge/?path=/story/forms-form-group--form-group
> fix(shadows): update components with correct shadow

- src/__tests__/ui-select.test.js
Initial test for select component
> test(select): add initial select test

- src/__tests__/ui-input.test.js
- src/__tests__/ui-select.test.js
Add initial unit test for ui-input and check prop on ui-select
> test(input): add unit test for ui-input

- src/__tests__/ui-input.test.js
- src/components/ui-input.vue
https://vuejs.org/v2/guide/components.html#Using-v-model-on-Components
> fix(input): add v-model support

- src/__tests__/ui-select.test.js
- src/components/ui-select.vue
- src/stories/ui-select.stories.js
BREAKING CHANGE: selected value use prop value instead of selected
> fix(select): add v-model support

- package-lock.json
- src/__tests__/ui-input.test.js
- src/components/ui-input.vue
- src/stories/ui-input.stories.js
> feat(ui-input): change typo in name

- package-lock.json
- src/__tests__/ui-modal.test.js
- src/components/ui-modal.vue
- src/stories/ui-modal.stories.js
Add the possibility to pass any text to replace the default 'X' icon to close the modal.
> feat(modal_close_button): add text option for close modal button
